In [1]:
# Q1
'''You use ordinal encoding to preserve order of categorical data i.e. cold, warm, hot; low, medium, high.
You use label encoding or one hot for categorical data, where there's no order in data i.e. dog, cat, whale. 
 Example:
     red is 1, green is 2, and blue is 3. This is called an ordinal encoding or an integer encoding and
     is easily reversible. Often, integer values starting at zero are used. For some variables, an ordinal encoding may be 
     enough.
    
     and if we talk about degree or qualification of a person we will give rank it (but in the above case we can't rank it.)
     so, in this we use a label encoder.
'''

"You use ordinal encoding to preserve order of categorical data i.e. cold, warm, hot; low, medium, high.\nYou use label encoding or one hot for categorical data, where there's no order in data i.e. dog, cat, whale. \n Example:\n     red is 1, green is 2, and blue is 3. This is called an ordinal encoding or an integer encoding and\n     is easily reversible. Often, integer values starting at zero are used. For some variables, an ordinal encoding may be \n     enough.\n    \n     and if we talk about degree or qualification of a person we will give rank it (but in the above case we can't rank it.)\n     so, in this we use a label encoder.\n"

In [2]:
# Q2
'''Target Guided Ordinal Encoding:
   It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding
   technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this
   variable as a feature in our machine learning model.
    Example:'''
import pandas as pd
df = pd.DataFrame({'cloth':['jeans','shirt','pants','jaket','jeans','shirt','pants'],
                  'price':[500,450,490,700,900,750,1000]})
mean_price=df.groupby('cloth')['price'].mean().to_dict()
df['cloth_encoded']=df['cloth'].map(mean_price)
df[['price','cloth_encoded']]

price  cloth_encoded
0    500          700.0
1    450          600.0
2    490          745.0
3    700          700.0
4    900          700.0
5    750          600.0
6   1000          745.0

In [3]:
# Q3
'''Covariance is a measure of the relationship between two random variables and to what extent, they change together. Or we 
   can say, in other words, it defines the changes between the two variables, such that change in one variable is equal to
   change in another variable.
   To calculate covariance, you can use the formula:
    Cov(X, Y) = Σ(Xi-µ)(Yj-v) / n.
    '''

'Covariance is a measure of the relationship between two random variables and to what extent, they change together. Or we \n   can say, in other words, it defines the changes between the two variables, such that change in one variable is equal to\n   change in another variable.\n   To calculate covariance, you can use the formula:\n    Cov(X, Y) = Σ(Xi-µ)(Yj-v) / n.\n    '

In [13]:
# Q4
import pandas as pd
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()
df = pd.DataFrame({'Color':['red', 'green', 'blue'], 'Size':['small', 'medium', 'large'],
                   'Material':['wood', 'metal', 'plastic']})
lbl_encoder.fit_transform(df[['Color']]),lbl_encoder.fit_transform(df[['Size']]),lbl_encoder.fit_transform(df[['Material']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([2, 1, 0]), array([2, 1, 0]), array([2, 0, 1]))

In [19]:
# Q5
import numpy as np
 
age = np.array([12,15,16,17,19,20])
income = np.array([0,0,10000,15000,25000,24000])
Education_level = np.array([6,10,11,12])
print("Covariance matrix of age:", np.cov(age))
print("Covariance matrix of income:", np.cov(income))
print("Covariance matrix of Education_level:", np.cov(Education_level))

Covariance matrix of age: 8.3
Covariance matrix of income: 122666666.66666666
Covariance matrix of Education_level: 6.916666666666666


In [24]:
# Q6
'For gender:-- in this we use nominal encoding'
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({
    'gender': ['female', 'male']
})
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['gender']]).toarray()
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoder_df           

gender_female  gender_male
0            1.0          0.0
1            0.0          1.0

In [33]:
'For education level:--In this we use ordinal encoding because it need rank.'
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({
    'Education_level' : ['High School','Bachelors','Masters','PhD']
})
encoder=OrdinalEncoder(categories=[['High School','Bachelors','Masters','PhD']])
encoder.fit_transform(df[['Education_level']])

array([[0.],
       [1.],
       [2.],
       [3.]])

In [31]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({
    'Employment_status':['Unemployed','Part-Time','Full-Time']
})
encoder=OrdinalEncoder(categories=[['Unemployed','Part-Time','Full-Time']])
encoder.fit_transform(df[['Employment_status']])

array([[0.],
       [1.],
       [2.]])

In [2]:
# Q7
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({
              "Weather_condition":['Sunny','Cloudy','Rainy']
})
encoder=OrdinalEncoder(categories=[['Sunny','Cloudy','Rainy']])
encoder.fit_transform(df[["Weather_condition"]])

array([[0.],
       [1.],
       [2.]])

In [3]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({
              "Weather_condition":['Sunny','Cloudy','Rainy']
})
encoder=OrdinalEncoder(categories=[['Sunny','Cloudy','Rainy']])
encoder.fit_transform(df[["Weather_condition"]])

array([[0.],
       [1.],
       [2.]])

In [ ]:
import numpy as np
 
temp = np.array([12,15,26,17,19,20])
humidity = np.array([95,86,75,83,])
Education_level = np.array([6,10,11,12])
print("Covariance matrix of age:", np.cov(age))
print("Covariance matrix of income:", np.cov(income))